name: Testing
on:
  push:
    branches:
      - "main"

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Install Libs
        run: |
          python -m pip install -r dev-requirements.txt
      - name: "Linting"
        run: |
          pycodestyle *.py
          pycodestyle tests/
          pycodestyle examples/
          pycodestyle src/
      # - name: "Unit Testing"
      #   run: |
      #     python -m pytest tests/